const W=595.276,H=841.89;
const fields=[
{id:'solicito',label:'Solicito',placeholder:'Ej. Constancia de estudios',step:0,box:[249,122,306,31],multi:true},
{id:'autoridad',label:'Autoridad a quien se dirige',placeholder:'Ej. Decano de la Facultad de Ingeniería',step:0,box:[34,237,526,14]},
{id:'nombre',label:'Nombres y apellidos',placeholder:'Escribe tu nombre completo',step:1,box:[34,288,526,14]},
{id:'condicion',label:'Condición del usuario',placeholder:'Docente, administrativo, alumno, exalumno u otro',step:1,box:[34,339,526,14]},
{id:'dni',label:'DNI',placeholder:'Número de documento',step:1,box:[34,388,243,14]},
{id:'telefono',label:'Teléfono / celular',placeholder:'Número de contacto',step:1,box:[317,388,243,14]},
{id:'domicilio',label:'Domicilio',placeholder:'Jr., avenida, calle, urbanización y distrito',step:1,box:[34,439,526,14]},
{id:'email',label:'Correo electrónico',placeholder:'nombre@correo.com',step:1,box:[34,490,526,14]},
{id:'fundamento',label:'Fundamento del pedido',placeholder:'Explica tu solicitud y las razones que la sustentan…',step:0,box:[35,542,524,129],multi:true},
{id:'adjuntos',label:'Documentos que se adjuntan',placeholder:'Ej. Copia de DNI\nRecibo de pago',step:2,box:[35,714,242,100],multi:true},
{id:'fecha',label:'Lugar y fecha',placeholder:'Ej. Huánuco, 5 de octubre de 2026',step:2,box:[317,712,243,14]},
{id:'firma',label:'Firma del usuario',step:2,box:[317,758,243,56],signature:true}
];
function currentPlaceAndDate(){return 'Huánuco, '+new Intl.DateTimeFormat('es-PE',{day:'numeric',month:'long',year:'numeric',timeZone:'America/Lima'}).format(new Date())}
const values=Object.fromEntries(fields.map(f=>[f.id,f.id==='fecha'?currentPlaceAndDate():'']));let step=0,font,signature=null,isDrawing=false,hasInk=false;
const form=document.querySelector('#form'),paper=document.querySelector('#paper'),status=document.querySelector('#status');
const ready=(async()=>{const d=await PDFLib.PDFDocument.create();font=await d.embedFont(PDFLib.StandardFonts.Helvetica);})();
function normalize(s){return s.normalize('NFC').replace(/\t/g,'    ')}
function wrap(text,size,width){const out=[];for(const paragraph of text.split('\n')){let line='';for(const word of paragraph.split(/ +/)){if(!word)continue;let chunks=[word];if(font.widthOfTextAtSize(word,size)>width){chunks=[];let part='';for(const c of word){if(font.widthOfTextAtSize(part+c,size)>width&&part){chunks.push(part);part=''}part+=c}if(part)chunks.push(part)}for(const chunk of chunks){const next=line?line+' '+chunk:chunk;if(font.widthOfTextAtSize(next,size)>width&&line){out.push(line);line=chunk}else line=next}}out.push(line)}return out}
function fit(f){if(!font||!values[f.id])return null;const text=normalize(values[f.id]);try{font.encodeText(text.replace(/\n/g,''));for(let size=12;size>=6;size-=.25){const lines=wrap(text,size,f.box[2]);if(lines.length*size*1.2<=f.box[3])return {size,lines}}return {error:'Hay demasiado texto en «'+f.label+'». Acórtalo para que siga siendo legible.'}}catch{return {error:'«'+f.label+'» contiene un símbolo no compatible. Usa letras, números y signos de puntuación habituales.'}}}
function update(){let errors=[];for(const f of fields){const el=document.getElementById('preview-'+f.id);if(f.signature){el.innerHTML='';if(signature){const im=document.createElement('img');im.src=signature;im.style.cssText='width:100%;height:100%;object-fit:contain';el.append(im)}continue}const layout=fit(f);el.classList.toggle('empty',!values[f.id]);el.textContent=layout&&!layout.error?layout.lines.join('\n'):'';if(layout&&!layout.error)el.style.fontSize=(layout.size/W*paper.clientWidth)+'px';if(layout?.error)errors.push(layout.error)}document.querySelector('#count').textContent=fields.filter(f=>f.signature?signature:values[f.id].trim()).length+' / 12';status.textContent=errors[0]||'';document.querySelector('#download').disabled=errors.length>0}
function render(){form.innerHTML='';const title=document.createElement('div');title.className='group-heading';title.innerHTML='<span>'+['▤','◉','✓'][step]+'</span>'+['¿Qué necesitas solicitar?','Información del solicitante','Adjuntos, fecha y firma'][step];form.append(title);fields.filter(f=>f.step===step).forEach(f=>{const div=document.createElement('div');div.className='field';const label=document.createElement('label');label.htmlFor=f.id;label.innerHTML='<small>'+String(fields.indexOf(f)+1).padStart(2,'0')+'</small>'+f.label;div.append(label);if(f.signature){const c=document.createElement('canvas');c.id='firma';c.width=900;c.height=260;c.setAttribute('aria-label','Dibuja tu firma con el ratón o el dedo');div.append(c);const actions=document.createElement('div');actions.className='sig-actions';actions.innerHTML='<span>Firma con el ratón o el dedo.</span><button class="text-button" type="button">Borrar firma</button>';div.append(actions);actions.querySelector('button').onclick=()=>{c.getContext('2d').clearRect(0,0,c.width,c.height);signature=null;hasInk=false;update()};const ctx=c.getContext('2d');ctx.lineWidth=3;ctx.lineCap='round';ctx.strokeStyle='#171717';if(signature){const im=new Image();im.onload=()=>ctx.drawImage(im,0,0,c.width,c.height);im.src=signature}const point=e=>{const r=c.getBoundingClientRect();return [(e.clientX-r.left)*c.width/r.width,(e.clientY-r.top)*c.height/r.height]};c.onpointerdown=e=>{e.preventDefault();c.setPointerCapture(e.pointerId);isDrawing=true;ctx.beginPath();ctx.moveTo(...point(e));ctx.lineTo(...point(e));ctx.stroke();hasInk=true};c.onpointermove=e=>{if(!isDrawing)return;ctx.lineTo(...point(e));ctx.stroke()};c.onpointerup=c.onpointercancel=()=>{if(!isDrawing)return;isDrawing=false;signature=hasInk?c.toDataURL('image/png'):null;update()}}else{const input=document.createElement(f.multi?'textarea':'input');input.id=f.id;input.placeholder=f.placeholder;input.value=values[f.id];input.maxLength=f.id==='fundamento'?6000:2000;if(f.id==='dni'||f.id==='telefono')input.inputMode='numeric';if(f.id==='email')input.inputMode='email';if(f.id==='fundamento')input.rows=7;input.oninput=()=>{values[f.id]=input.value;update()};div.append(input);if(f.id==='fecha'){const hint=document.createElement('div');hint.className='hint';hint.textContent='Fecha de hoy en Huánuco. Puedes cambiar el lugar y la fecha.';div.append(hint)}if(f.multi){const hint=document.createElement('div');hint.className='hint';hint.textContent='El tamaño de letra se ajusta al espacio disponible.';div.append(hint)}}form.append(div)});document.querySelectorAll('[data-step]').forEach(b=>{const selected=Number(b.dataset.step)===step;b.classList.toggle('selected',selected);b.setAttribute('aria-selected',String(selected))});document.querySelector('#next').textContent=step===2?'Descargar PDF':'Continuar';update()}
fields.forEach(f=>{const el=document.createElement('div');el.id='preview-'+f.id;el.className='paper-field empty';const [x,y,w,h]=f.box;el.style.cssText=`left:${x/W*100}%;top:${y/H*100}%;width:${w/W*100}%;height:${h/H*100}%`;el.tabIndex=0;el.setAttribute('role','button');el.setAttribute('aria-label','Editar '+f.label);const select=()=>{step=f.step;render();document.getElementById(f.id)?.focus();if(innerWidth<850)document.querySelector('.editor').scrollIntoView({behavior:'smooth',block:'start'})};el.onclick=select;el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();select()}};document.querySelector('#overlays').append(el)});
document.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>{step=Number(b.dataset.step);render()});form.onsubmit=e=>e.preventDefault();document.querySelector('#next').onclick=()=>{if(step===2)download();else{step++;render();if(innerWidth<850)document.querySelector('.editor').scrollIntoView({behavior:'smooth',block:'start'})}};document.querySelector('#reset').onclick=()=>{if(!fields.some(f=>values[f.id])&&!signature)return;if(confirm('¿Quieres borrar todos los datos y la firma?')){fields.forEach(f=>values[f.id]=f.id==='fecha'?currentPlaceAndDate():'');signature=null;hasInk=false;render()}};document.querySelector('#zoom').onclick=()=>{const panel=document.querySelector('.preview-panel');panel.classList.toggle('expanded');document.querySelector('#zoom').textContent=panel.classList.contains('expanded')?'Reducir':'Ampliar';update()};document.querySelector('#tool').onclick=()=>document.querySelector('.editor').scrollIntoView({behavior:'smooth'});new ResizeObserver(update).observe(paper);
async function download(){const btn=document.querySelector('#download');try{await ready;const layouts=fields.map(f=>f.signature?null:fit(f));const error=layouts.find(l=>l?.error);if(error){status.textContent=error.error;return}btn.disabled=true;btn.textContent='Preparando PDF…';status.textContent='';const response=await fetch('fut-original.pdf');if(!response.ok)throw Error('No se pudo abrir el formulario original.');const doc=await PDFLib.PDFDocument.load(await response.arrayBuffer());const page=doc.getPages()[0];const exportFont=await doc.embedFont(PDFLib.StandardFonts.Helvetica);for(let i=0;i<fields.length;i++){const f=fields[i];const [x,y,w,h]=f.box;if(f.signature){if(signature){const im=await doc.embedPng(signature);const scale=Math.min(w/im.width,h/im.height);page.drawImage(im,{x:x+(w-im.width*scale)/2,y:H-y-h+(h-im.height*scale)/2,width:im.width*scale,height:im.height*scale})}continue}const l=layouts[i];if(!l)continue;page.drawRectangle({x,y:H-y-h,width:w,height:h,color:PDFLib.rgb(1,1,1)});l.lines.forEach((line,index)=>page.drawText(line,{x,y:H-y-l.size-index*l.size*1.2,size:l.size,font:exportFont,color:PDFLib.rgb(.08,.08,.08)}))}const bytes=await doc.save();const url=URL.createObjectURL(new Blob([bytes],{type:'application/pdf'}));const a=document.createElement('a');a.href=url;a.download='FUT-Grafiplot.pdf';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);status.textContent='PDF descargado. Revisa tus datos antes de presentarlo.'}catch(e){status.textContent='No se pudo generar el PDF. '+e.message}finally{btn.innerHTML='<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5"/></svg> Descargar PDF';btn.disabled=false}}
document.querySelector('#download').onclick=download;ready.then(render).catch(()=>{status.textContent='No se pudo iniciar el editor. Recarga la página.'});
